### ISSUE TITLE
gilbert serve has clickable link for invalid url

### ISSUE THREAD

**Issue by flyladyhawke** [funkybob/gilbert#32]
on windows 7 and pycharm:
Part of the message is the below where the text in brackets is a clickable link)
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...

This url is invalid, and may be confusing to someone reading the output.

**Comment by funkybob** [comment]
I've now reworked the "serve" command to allow you to specify the port and address, and removed the misleading link from the message.
